import { defineConfig } from 'tinacms';

export default defineConfig({
    branch: process.env.NEXT_PUBLIC_TINA_BRANCH || 'main',
    clientId: process.env.NEXT_PUBLIC_TINA_CLIENT_ID || '00000000-0000-0000-0000-000000000000',
    token: process.env.TINA_TOKEN || 'dummy_token',

    build: {
        outputFolder: 'admin',
        publicFolder: 'public',
    },

    media: {
        tina: {
            mediaRoot: 'images',
            publicFolder: 'public',
        },
    },

    schema: {
        collections: [
            {
                name: 'homepage',
                label: 'Homepage',
                path: 'content/homepage',
                format: 'json',
                ui: {
                    global: true,
                    allowedActions: { create: false, delete: false },
                    filename: {
                        readonly: true,
                        slugify: () => 'index',
                    },
                },
                fields: [
                    {
                        type: 'object',
                        name: 'hero',
                        label: 'Hero Section',
                        fields: [
                            { type: 'string', name: 'badge', label: 'Badge' },
                            { type: 'string', name: 'badgeBg', label: 'Badge Background', ui: { component: 'color' } },
                            { type: 'string', name: 'badgeText', label: 'Badge Text Color', ui: { component: 'color' } },
                            { type: 'number', name: 'badgeSize', label: 'Badge Font Size (px)' },
                            { type: 'string', name: 'badgeFont', label: 'Badge Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'headline', label: 'Headline' },
                            { type: 'string', name: 'headlineColor', label: 'Headline Color', ui: { component: 'color' } },
                            { type: 'number', name: 'headlineSize', label: 'Headline Font Size (px)' },
                            { type: 'string', name: 'headlineFont', label: 'Headline Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'accent', label: 'Headline Accent' },
                            { type: 'string', name: 'accentColor', label: 'Accent Text Color', ui: { component: 'color' } },
                            { type: 'string', name: 'subtext', label: 'Subtext' },
                            { type: 'string', name: 'subtextColor', label: 'Subtext Color', ui: { component: 'color' } },
                            { type: 'number', name: 'subtextSize', label: 'Subtext Font Size (px)' },
                            { type: 'string', name: 'subtextFont', label: 'Subtext Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'primaryCtaText', label: 'Primary CTA Text' },
                            { type: 'string', name: 'primaryCtaLink', label: 'Primary CTA Link' },
                            { type: 'string', name: 'primaryBtnBg', label: 'Primary Button Background', ui: { component: 'color' } },
                            { type: 'string', name: 'primaryBtnText', label: 'Primary Button Text Color', ui: { component: 'color' } },
                            { type: 'number', name: 'primaryBtnSize', label: 'Primary Button Font Size (px)' },
                            { type: 'string', name: 'secondaryCtaText', label: 'Secondary CTA Text' },
                            { type: 'string', name: 'secondaryCtaLink', label: 'Secondary CTA Link' },
                            { type: 'string', name: 'secondaryBtnBorder', label: 'Secondary Button Border Color', ui: { component: 'color' } },
                            { type: 'string', name: 'secondaryBtnText', label: 'Secondary Button Text Color', ui: { component: 'color' } },
                            { type: 'number', name: 'secondaryBtnSize', label: 'Secondary Button Font Size (px)' },
                            { type: 'image', name: 'backgroundImage', label: 'Background Image' },
                            { type: 'string', name: 'overlayColor', label: 'Overlay Color', ui: { component: 'color' } },
                            { type: 'number', name: 'overlayOpacity', label: 'Overlay Opacity (0-1)' },
                        ],
                    },
                    {
                        type: 'object',
                        name: 'categories',
                        label: 'Categories Section',
                        fields: [
                            { type: 'string', name: 'label', label: 'Section Label' },
                            { type: 'string', name: 'labelColor', label: 'Label Color', ui: { component: 'color' } },
                            { type: 'number', name: 'labelSize', label: 'Label Font Size (px)' },
                            { type: 'string', name: 'labelFont', label: 'Label Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'title', label: 'Section Title' },
                            { type: 'string', name: 'titleColor', label: 'Title Color', ui: { component: 'color' } },
                            { type: 'number', name: 'titleSize', label: 'Title Font Size (px)' },
                            { type: 'string', name: 'titleFont', label: 'Title Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'subtitle', label: 'Section Subtitle' },
                            { type: 'string', name: 'subtitleColor', label: 'Subtitle Color', ui: { component: 'color' } },
                            { type: 'number', name: 'subtitleSize', label: 'Subtitle Font Size (px)' },
                            { type: 'string', name: 'subtitleFont', label: 'Subtitle Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            {
                                type: 'object',
                                name: 'items',
                                label: 'Category Items',
                                list: true,
                                fields: [
                                    { type: 'string', name: 'title', label: 'Title' },
                                    { type: 'string', name: 'subtitle', label: 'Subtitle' },
                                    { type: 'string', name: 'href', label: 'Link' },
                                    { type: 'string', name: 'bg', label: 'Fallback Background Color (Hex)', ui: { component: 'color' } },
                                    { type: 'image', name: 'image', label: 'Image' },
                                ],
                            },
                            { type: 'string', name: 'sectionBg', label: 'Section Background Color', ui: { component: 'color' } },
                            { type: 'string', name: 'cardBg', label: 'Card Background', ui: { component: 'color' } },
                            { type: 'string', name: 'cardTitleColor', label: 'Card Title Color', ui: { component: 'color' } },
                            { type: 'string', name: 'cardSubColor', label: 'Card Subtitle Color', ui: { component: 'color' } },
                        ],
                    },
                    {
                        type: 'object',
                        name: 'trust',
                        label: 'Trust Section',
                        fields: [
                            { type: 'string', name: 'label', label: 'Section Label' },
                            { type: 'string', name: 'labelColor', label: 'Label Color', ui: { component: 'color' } },
                            { type: 'number', name: 'labelSize', label: 'Label Font Size (px)' },
                            { type: 'string', name: 'labelFont', label: 'Label Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'title', label: 'Section Title' },
                            { type: 'string', name: 'titleColor', label: 'Title Color', ui: { component: 'color' } },
                            { type: 'number', name: 'titleSize', label: 'Title Font Size (px)' },
                            { type: 'string', name: 'titleFont', label: 'Title Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            {
                                type: 'object',
                                name: 'items',
                                label: 'Trust Items',
                                list: true,
                                fields: [
                                    { type: 'string', name: 'icon', label: 'Icon (emoji/text)' },
                                    { type: 'string', name: 'title', label: 'Title' },
                                    {
                                        type: 'string',
                                        name: 'desc',
                                        label: 'Description',
                                        ui: { component: 'textarea' },
                                    },
                                ],
                            },
                            { type: 'string', name: 'sectionBg', label: 'Section Background Color', ui: { component: 'color' } },
                            { type: 'string', name: 'cardBg', label: 'Card Background', ui: { component: 'color' } },
                            { type: 'string', name: 'cardTitleColor', label: 'Card Title Color', ui: { component: 'color' } },
                            { type: 'string', name: 'cardDescColor', label: 'Card Description Color', ui: { component: 'color' } },
                            { type: 'string', name: 'iconColor', label: 'Icon Color', ui: { component: 'color' } },
                            { type: 'string', name: 'iconBg', label: 'Icon Background', ui: { component: 'color' } },
                        ],
                    },
                    {
                        type: 'object',
                        name: 'studio',
                        label: 'Studio Section',
                        fields: [
                            { type: 'string', name: 'label', label: 'Section Label' },
                            { type: 'string', name: 'labelColor', label: 'Label Color', ui: { component: 'color' } },
                            { type: 'number', name: 'labelSize', label: 'Label Font Size (px)' },
                            { type: 'string', name: 'labelFont', label: 'Label Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'title', label: 'Section Title' },
                            { type: 'string', name: 'titleColor', label: 'Title Color', ui: { component: 'color' } },
                            { type: 'number', name: 'titleSize', label: 'Title Font Size (px)' },
                            { type: 'string', name: 'titleFont', label: 'Title Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            {
                                type: 'string',
                                name: 'text',
                                label: 'Description',
                                ui: { component: 'textarea' },
                            },
                            { type: 'string', name: 'textColor', label: 'Description Color', ui: { component: 'color' } },
                            { type: 'number', name: 'textSize', label: 'Description Font Size (px)' },
                            { type: 'string', name: 'textFont', label: 'Description Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            {
                                type: 'string',
                                name: 'features',
                                label: 'Feature List',
                                list: true,
                            },
                            { type: 'string', name: 'featureIconColor', label: 'Feature Icon Color', ui: { component: 'color' } },
                            { type: 'string', name: 'featureTextColor', label: 'Feature Text Color', ui: { component: 'color' } },
                            { type: 'string', name: 'ctaText', label: 'CTA Text' },
                            { type: 'string', name: 'ctaLink', label: 'CTA Link' },
                            { type: 'string', name: 'ctaBg', label: 'CTA Button Background', ui: { component: 'color' } },
                            { type: 'string', name: 'ctaTextColor', label: 'CTA Button Text Color', ui: { component: 'color' } },
                            {
                                type: 'image',
                                name: 'images',
                                label: 'Grid Images (Max 4 recommended)',
                                list: true,
                            },
                            { type: 'string', name: 'sectionBg', label: 'Section Background Color', ui: { component: 'color' } },
                        ],
                    },
                    {
                        type: 'object',
                        name: 'cta',
                        label: 'Bottom CTA Section',
                        fields: [
                            { type: 'string', name: 'label', label: 'Section Label' },
                            { type: 'string', name: 'labelColor', label: 'Label Color', ui: { component: 'color' } },
                            { type: 'number', name: 'labelSize', label: 'Label Font Size (px)' },
                            { type: 'string', name: 'labelFont', label: 'Label Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'title', label: 'Section Title' },
                            { type: 'string', name: 'titleColor', label: 'Title Color', ui: { component: 'color' } },
                            { type: 'number', name: 'titleSize', label: 'Title Font Size (px)' },
                            { type: 'string', name: 'titleFont', label: 'Title Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            {
                                type: 'string',
                                name: 'subtitle',
                                label: 'Section Subtitle',
                                ui: { component: 'textarea' },
                            },
                            { type: 'string', name: 'subtitleColor', label: 'Subtitle Color', ui: { component: 'color' } },
                            { type: 'number', name: 'subtitleSize', label: 'Subtitle Font Size (px)' },
                            { type: 'string', name: 'subtitleFont', label: 'Subtitle Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'primaryText', label: 'Primary Button Text' },
                            { type: 'string', name: 'primaryLink', label: 'Primary Button Link' },
                            { type: 'string', name: 'primaryBtnBg', label: 'Primary Button Background', ui: { component: 'color' } },
                            { type: 'string', name: 'primaryBtnText', label: 'Primary Button Text Color', ui: { component: 'color' } },
                            { type: 'string', name: 'secondaryText', label: 'Secondary Button Text' },
                            { type: 'string', name: 'secondaryLink', label: 'Secondary Button Link' },
                            { type: 'string', name: 'secondaryBtnBorder', label: 'Secondary Button Border Color', ui: { component: 'color' } },
                            { type: 'string', name: 'secondaryBtnText', label: 'Secondary Button Text Color', ui: { component: 'color' } },
                            { type: 'string', name: 'sectionBg', label: 'Section Background Color', ui: { component: 'color' } },
                        ],
                    },
                    {
                        type: 'object',
                        name: 'reviews',
                        label: 'Reviews Section (Homepage)',
                        fields: [
                            { type: 'string', name: 'label', label: 'Section Label' },
                            { type: 'string', name: 'labelColor', label: 'Label Color', ui: { component: 'color' } },
                            { type: 'number', name: 'labelSize', label: 'Label Font Size (px)' },
                            { type: 'string', name: 'labelFont', label: 'Label Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'title', label: 'Section Title' },
                            { type: 'string', name: 'titleColor', label: 'Title Color', ui: { component: 'color' } },
                            { type: 'number', name: 'titleSize', label: 'Title Font Size (px)' },
                            { type: 'string', name: 'titleFont', label: 'Title Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'sectionBg', label: 'Section Background Color', ui: { component: 'color' } },
                        ],
                    },
                ],
            },
            {
                name: 'project',
                label: 'Projects',
                path: 'content/projects',
                format: 'json',
                fields: [
                    {
                        type: 'string',
                        name: 'title',
                        label: 'Project Title',
                        isTitle: true,
                        required: true,
                    },
                    { type: 'string', name: 'titleColor', label: 'Title Color', ui: { component: 'color' } },
                    { type: 'number', name: 'titleSize', label: 'Title Font Size (px)' },
                    { type: 'string', name: 'titleFont', label: 'Title Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                    {
                        type: 'string',
                        name: 'description',
                        label: 'Description',
                        ui: { component: 'textarea' },
                    },
                    { type: 'string', name: 'descColor', label: 'Description Color', ui: { component: 'color' } },
                    { type: 'number', name: 'descSize', label: 'Description Font Size (px)' },
                    { type: 'string', name: 'descFont', label: 'Description Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                    { type: 'string', name: 'cardBg', label: 'Card Background Color', ui: { component: 'color' } },
                    {
                        type: 'string',
                        name: 'category',
                        label: 'Category',
                        options: ['مطابخ', 'غرف ملابس', 'وحدات تلفزيون', 'تصميمات خاصة'],
                    },
                    {
                        type: 'string',
                        name: 'completionDate',
                        label: 'Completion Date',
                    },
                    {
                        type: 'image',
                        name: 'images',
                        label: 'Images',
                        list: true,
                    },
                ],
            },
            {
                name: 'review',
                label: 'Reviews',
                path: 'content/reviews',
                format: 'json',
                fields: [
                    {
                        type: 'string',
                        name: 'quote',
                        label: 'Quote',
                        ui: { component: 'textarea' },
                    },
                    { type: 'string', name: 'quoteColor', label: 'Quote Color', ui: { component: 'color' } },
                    { type: 'number', name: 'quoteSize', label: 'Quote Font Size (px)' },
                    { type: 'string', name: 'quoteFont', label: 'Quote Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                    {
                        type: 'string',
                        name: 'name',
                        label: 'Client Name',
                        isTitle: true,
                        required: true,
                    },
                    { type: 'string', name: 'nameColor', label: 'Name Color', ui: { component: 'color' } },
                    { type: 'number', name: 'nameSize', label: 'Name Font Size (px)' },
                    {
                        type: 'string',
                        name: 'location',
                        label: 'Location',
                    },
                    { type: 'string', name: 'locationColor', label: 'Location Color', ui: { component: 'color' } },
                    { type: 'number', name: 'locationSize', label: 'Location Font Size (px)' },
                    {
                        type: 'number',
                        name: 'rating',
                        label: 'Rating (1-5)',
                    },
                    { type: 'string', name: 'starColor', label: 'Star Rating Color', ui: { component: 'color' } },
                    { type: 'string', name: 'cardBg', label: 'Card Background Color', ui: { component: 'color' } },
                ],
            },
            {
                name: 'settings',
                label: 'Settings',
                path: 'content/settings',
                format: 'json',
                ui: {
                    global: true,
                    allowedActions: { create: false, delete: false },
                    filename: {
                        readonly: true,
                        slugify: () => 'index',
                    },
                },
                fields: [
                    { type: 'string', name: 'brandName', label: 'Brand Name' },
                    { type: 'image', name: 'customFont', label: 'Upload Custom Font (.ttf)' },
                    { type: 'string', name: 'goldColor', label: 'Default Accent Color', ui: { component: 'color' } },
                    { type: 'string', name: 'phone', label: 'Phone' },
                    { type: 'string', name: 'email', label: 'Email' },
                    { type: 'string', name: 'location', label: 'Location' },
                    { type: 'string', name: 'whatsapp', label: 'WhatsApp Number' },
                    { type: 'string', name: 'instagram', label: 'Instagram Link' },
                    { type: 'string', name: 'facebook', label: 'Facebook Link' },
                    { type: 'string', name: 'tiktok', label: 'TikTok Link' },
                    { type: 'string', name: 'twitter', label: 'X (Twitter) Link' },
                    { type: 'string', name: 'pinterest', label: 'Pinterest Link' },
                    { type: 'string', name: 'footerBg', label: 'Footer Background', ui: { component: 'color' } },
                    { type: 'string', name: 'footerTitleColor', label: 'Footer Title Color', ui: { component: 'color' } },
                    { type: 'number', name: 'footerTitleSize', label: 'Footer Title Font Size (px)' },
                    { type: 'string', name: 'footerTitleFont', label: 'Footer Title Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                    { type: 'string', name: 'footerTextColor', label: 'Footer Text Color', ui: { component: 'color' } },
                    { type: 'number', name: 'footerTextSize', label: 'Footer Text Font Size (px)' },
                    { type: 'string', name: 'footerTextFont', label: 'Footer Text Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                    { type: 'string', name: 'footerLinkColor', label: 'Footer Link Color', ui: { component: 'color' } },
                    { type: 'number', name: 'footerLinkSize', label: 'Footer Link Font Size (px)' },
                    { type: 'string', name: 'footerLinkFont', label: 'Footer Link Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                    { type: 'string', name: 'footerSocialColor', label: 'Footer Social Icon Color', ui: { component: 'color' } },
                    { type: 'string', name: 'categories', label: 'Global Categories (comma separated)', list: true },
                    {
                        type: 'object',
                        name: 'portfolio',
                        label: 'Portfolio Page Header',
                        fields: [
                            { type: 'string', name: 'label', label: 'Page Label' },
                            { type: 'string', name: 'labelColor', label: 'Label Color', ui: { component: 'color' } },
                            { type: 'number', name: 'labelSize', label: 'Label Font Size (px)' },
                            { type: 'string', name: 'labelFont', label: 'Label Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'title', label: 'Page Title' },
                            { type: 'string', name: 'titleColor', label: 'Title Color', ui: { component: 'color' } },
                            { type: 'number', name: 'titleSize', label: 'Title Font Size (px)' },
                            { type: 'string', name: 'titleFont', label: 'Title Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'subtitle', label: 'Page Subtitle' },
                            { type: 'string', name: 'subtitleColor', label: 'Subtitle Color', ui: { component: 'color' } },
                            { type: 'number', name: 'subtitleSize', label: 'Subtitle Font Size (px)' },
                            { type: 'string', name: 'subtitleFont', label: 'Subtitle Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'sectionBg', label: 'Header Background Color', ui: { component: 'color' } },
                        ],
                    },
                    {
                        type: 'object',
                        name: 'header',
                        label: 'Header Settings',
                        fields: [
                            { type: 'image', name: 'logoImage', label: 'Logo Image (Replaces Text)' },
                            { type: 'string', name: 'logoText', label: 'Logo Text (English)' },
                            { type: 'string', name: 'logoColor', label: 'Logo Color (English)', ui: { component: 'color' } },
                            { type: 'number', name: 'logoEnSize', label: 'English Logo Font Size (px)' },
                            { type: 'string', name: 'logoFont', label: 'Logo Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'logoAr', label: 'Logo Text (Arabic)' },
                            { type: 'string', name: 'logoArColor', label: 'Logo Color (Arabic)', ui: { component: 'color' } },
                            { type: 'number', name: 'logoArSize', label: 'Arabic Logo Font Size (px)' },
                            {
                                type: 'object',
                                name: 'navLinks',
                                label: 'Navigation Links',
                                list: true,
                                fields: [
                                    { type: 'string', name: 'label', label: 'Link Label' },
                                    { type: 'string', name: 'href', label: 'Link Path' },
                                ],
                            },
                            { type: 'string', name: 'navLinkColor', label: 'Nav Link Color', ui: { component: 'color' } },
                            { type: 'number', name: 'navLinkSize', label: 'Nav Link Font Size (px)' },
                            { type: 'string', name: 'navLinkFont', label: 'Nav Link Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'ctaLabel', label: 'CTA Button Label' },
                            { type: 'string', name: 'ctaBg', label: 'CTA Button Background', ui: { component: 'color' } },
                            { type: 'string', name: 'ctaTextColor', label: 'CTA Button Text', ui: { component: 'color' } },
                            { type: 'number', name: 'ctaFontSize', label: 'CTA Button Font Size (px)' },
                            { type: 'string', name: 'ctaFont', label: 'CTA Button Font Family', options: [{ label: 'Inherit', value: 'inherit' }, { label: 'Custom Font', value: 'CustomFont' }] },
                            { type: 'string', name: 'headerBg', label: 'Header Background', ui: { component: 'color' } },
                        ],
                    },
                ],
            },
        ],
    },
});
